#
# *************************************************
# Copyright (c) 2019, Grindrod Bank Limited
# License MIT: https://opensource.org/licenses/MIT
# **************************************************
#

version: '3.4'
x-defaults: &defaults
  networks:
    - a3s-development
  restart: unless-stopped
  image: sentry:9.1
  depends_on:
    - redis
    - postgres
    - memcached
    # - smtp
  env_file: .env
  environment:
    SENTRY_MEMCACHED_HOST: memcached
    SENTRY_REDIS_HOST: redis
    SENTRY_POSTGRES_HOST: postgres
    # SENTRY_EMAIL_HOST: smtp
  # volumes:
  #   - sentry-data:/var/lib/sentry/files

services:
  memcached:
    networks:
      - a3s-development
    restart: unless-stopped
    image: memcached:1.5-alpine

  redis:
    networks:
      - a3s-development
    restart: unless-stopped
    image: redis:3.2-alpine

  postgres:
    networks:
      - a3s-development
    restart: unless-stopped
    image: postgres:9.5
    volumes:
      - sentry-postgres:/var/lib/postgresql/data

  web:
    <<: *defaults
    ports:
      - '9000:9000'

  cron:
    <<: *defaults
    command: run cron

  worker:
    <<: *defaults
    command: run worker

volumes:
   sentry-postgres:
     # external: true
      
networks:
  a3s-development: